# Jekyll Configuration
title: ""
description: "The 9th International Symposium on User Modeling and Language Learning"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

# Include/Exclude files
include:
  - _includes

# Collections
collections_dir: collections

# Defaults
# defaults:
#  - scope:
#      path: ""
#      type: "pages"
#    values:
#      layout: "default"
